<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="RavenDB.Client" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prius.Core\Prius.Core.csproj" />
    <ProjectReference Include="..\Prius.Core.Packages\Prius.Core.Packages.csproj" />
    <ProjectReference Include="..\Prius.Engine.Abstractions\Prius.Engine.Abstractions.csproj" />
  </ItemGroup>
</Project>
